import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.scss'

import { useState, useContext } from 'react';

import { Tabs, TabList, Tab, Text, Button, Box } from '@chakra-ui/react'
import Filters from '../components/Filters';
import Card from '../components/Card';

import Logo from '../public/logo.webp';

import { PageContext } from '../context';
import { getInfo, getRecomendation, getProviders } from '../context/actions';


const Home: NextPage = () => {
  const { dispatch, state: { selectedProvider = 0, fetching, recomendedContent = [], prevContent } } = useContext(PageContext);
  const [linkSelected, handleTabChange] = useState(0);
  const [source, setSource] = useState('movie');
  const [isFirst, setFirst] = useState(true);

  const getPageProviders = async () => {
    await getProviders(dispatch, source);
  }

  const handleTab = async (tab: number) => {
    if (tab !== linkSelected) {
      const newSource = tab === 0 ? 'movie' : 'tv';
      setFirst(true);
      handleTabChange(tab);
      setSource(newSource)
      getPageProviders();
      await getInfo(dispatch, newSource);
    }
  }

  const nextRecomendation = () => {
    setFirst(false);
    getRecomendation(dispatch, source, recomendedContent, prevContent, selectedProvider)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Que puedo ver?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Box margin="20px 0" width="100%" display="flex" alignItems="center" justifyContent="center">
          <Image src={Logo} height="150px" width="150px" />
        </Box>
        <Tabs defaultIndex={linkSelected} colorScheme="purple" size="lg" isFitted onChange={a => handleTab(a)}>
          <TabList>
            <Tab isSelected={linkSelected === 0}>Peliculas</Tab>
            <Tab isSelected={linkSelected === 1}>Series</Tab>
          </TabList>
        </Tabs>
      </header>
      <main className={styles.main}>
        <Text fontSize="xl" marginBottom="16px">{`${isFirst ? 'Tendencias de la semana' : 'Otras recomendaciones'}`}</Text>
        <Card source={source} />
        <Box margin="10px 0" width="100%" display="flex" justifyContent="flex-end">
          <Button onClick={nextRecomendation} disabled={fetching} size="sm" colorScheme='purple' variant='ghost'>Siguiente recomendación</Button>
        </Box>
        <Filters source={source} />
      </main>
      <footer className={styles.footer}>
        <Box display="flex" flexDirection="column" alignItems="center" justifyContent="center">
          <a
            href="https://www.themoviedb.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by
            <span className={styles.logo}>
              <img
                src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg"
                alt="THE MOVIE DB"
                width={72}
                height={16}
              />
            </span>
          </a>
          <Text color='gray.400' textAlign="center" style={{ fontSize: '10px' }}>This product uses the TMDB API but is not endorsed or certified by TMDB.</Text>
        </Box>
        <Box className={styles.dev}>
          Created by <a href='https://franciscodiazpaccot.com' target="_blank" rel="noreferrer noopener">
          Francisco Diaz Paccot</a>
        </Box>
      </footer>
    </div>
  )
}

export default Home
